return {
  kind_icons = {
    AI = "🧠",
    Array = "󱃵 ",
    Boolean = " ",
    Class = "󰗀 ",
    Color = " ",
    Control = " ",
    Collapsed = "祖",
    Constant = " ",
    Constructor = "﵅ ",
    Supermaven = " ",
    Enum = " ",
    EnumMember = " ",
    Event = "⚡",
    Field = "ﰠ ",
    File = " ",
    Folder = " ",
    Function = " ",
    Interface = " ",
    Key = " ",
    Keyword = "󰌋 ",
    Method = " ",
    Module = " ",
    Namespace = "ﬥ ",
    Null = " ",
    Number = " ",
    Object = " ",
    Operator = " ",
    Package = " ",
    Property = " ",
    Reference = " ",
    Snippet = " ",
    String = " ",
    Struct = " ",
    TabNine = "󰏚 ",
    Text = " ",
    TypeParameter = " ",
    Unit = " ",
    Value = "ﳚ ",
    Variable = "󱃻 ",
  },
  git = {
    added = " ",
    modified = " ",
    removed = " ",
  },
  misc = {
    dots = "󰇘",
  },

  diagnostics = {
    Error = " ",
    Warn = " ",
    Hint = " ",
    Info = " ",
  },
}
